# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cfe774017b08e884f640a77e1feed213b3b6ecf5c4a2f017ba338d3dc72717df88822eae4c827cefd7bd863354db3d6306dd3072db2741961460f4c037971ec

test:
  secret_key_base: 8b81fe55c837a60f01c1127ecbebdbe8427c5541c376f8f18092241fdac6485b2d9eb3292033af5aea1fe0eee9972749e9d2c26d2c49fff1962d1eedff46490b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
